import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';

const hostPath = path.resolve('public', 'codex-browser-host.js');

test('browser host retries transient Relay startup failures and republishes the Codex connection state', async () => {
  const source = await readFile(hostPath, 'utf8');
  assert.match(source, /const relaySessionAttempts = remoteDeviceRequested \? 20 : 8;/u);
  assert.match(source, /const retryableRelayStatuses = new Set\(\[409, 500, 502, 503\]\);/u);
  assert.match(source, /publishRelayConnectionState\('connected'\);/u);
  assert.match(source, /publishRelayConnectionState\('disconnected'\);/u);
  assert.match(source, /window\.codexLocalConnector\.syncRelayState\(\);/u);
  assert.match(source, /if \(relay\.state === 'connected'\) localConnector\.state = 'connected';/u);
  assert.match(source, /\? `已连接\$\{requestedDeviceLabel\}`/u);
  assert.match(source, /startRelaySession\(\{ force: true \}\)/u);
  assert.match(source, /connectHostRpcStream\(\)/u);
  assert.match(source, /const recoveryDelay = Math\.min\(10_000,/u);
  assert.match(source, /scheduleRelayRecovery\(recoveryError, \{ force: true \}\)/u);
  assert.match(source, /if \(relayRecoveryTimer\) clearTimeout\(relayRecoveryTimer\);/u);
  assert.match(source, /fetch\('\/api\/health', \{ credentials: 'include', cache: 'no-store' \}\)/u);
  assert.match(source, /if \(processId === observedServerProcessId\) return;/u);
  assert.match(source, /window\.location\.reload\(\);/u);
  assert.match(source, /serverEpochPollTimer = setInterval\(\(\) => void checkServerEpoch\(\), 2_500\);/u);
  assert.match(source, /error\?\.code === 'CODEX_RELAY_LEASE_EXPIRED'/u);
  assert.match(source, /syncRelayState\(\)/u);
  assert.match(source, /const sharedRelayRequested = Boolean\(sharedRelaySessionId && sharedRelayTicket && sharedRelayBrowserInstanceId\);/u);
  assert.match(source, /const embeddedProductRequested = query\.get\('embedded'\) === '1';/u);
  assert.match(source, /if \(embeddedProductRequested\) return;\s*selectLocalConnectorDevice\(online\.id\);/u);
  assert.match(source, /browserInstanceId: relayBrowserInstanceId/u);
  assert.match(source, /workspaces\/\$\{encodeURIComponent\(id\)\}\/threads/u);
  assert.match(source, /data-codex-product-workspace-action/u);
  assert.match(source, /Start task/u);
  assert.match(source, /method: 'thread\/started'/u);
  assert.match(source, /data-app-action-sidebar-project-list-id\^="product-"/u);
  assert.match(source, /empty\.dataset\.codexProductEmptyAction = 'true'/u);
  assert.match(source, /void startWorkspaceTask\(projectId\)/u);
  assert.doesNotMatch(source, /empty\.replaceChildren/u);
  assert.match(source, /pointer-events: none/u);
  assert.match(source, /pointer-events: auto/u);
  assert.match(source, /top: 72px;\s*bottom: auto;/u);
  assert.match(source, /shareLocalCodexSession\(\)/u);
  assert.match(source, /fetch\('\/api\/codex-relay\/invites'/u);
  assert.match(source, /复制一次性 Session 接入链接/u);
  assert.match(source, /startLocalConnectorLaunchFallback\(\);/u);
  assert.match(source, /未检测到连接器启动。请先下载并运行安装程序/u);
  assert.match(source, /startLocalConnectorConnectionFallback\(\);/u);
  assert.match(source, /连接器已启动，但本机 Relay 未上线/u);
  assert.match(source, /query\.get\('connector'\) === 'local'/u);
  assert.match(source, /destination\.searchParams\.set\('connector', 'local'\)/u);
  assert.match(source, /localDeviceRequested \? '本机设备' : '远程设备'/u);
});
